[package]
name = "edge-captcha-demo"
version = "0.2.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
fastly = "0.9.8"
http = "0.2.9"
captcha = "0.0.9"

lazy_static = "1.4.0"

hmac-sha256 = "1.1.7"
cookie = { version = "0.18.0", features = ["signed"] }
hex = "0.4.3"

